services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: beachbot
      POSTGRES_PASSWORD: beachbot
      POSTGRES_DB: beachbot_db
    volumes:
      - evolution_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  beachbot_pg:
